repos:
  - repo: local
    hooks:
      - id: commit-msg-validation
        name: Validate commit message format
        entry: bash scripts/commit-msg.sh
        language: system
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: pre-push-validation
        name: Validate commit message format before pushing
        entry: bash scripts/pre-push.sh
        language: system
        stages: [pre-push]
